// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIPEaxkYziXKOhkMKxCxIwtKkNQvg6V7E',
    appId: '1:182489347069:web:2ea7ebb83ab1e91ff79f94',
    messagingSenderId: '182489347069',
    projectId: 'crudfluets',
    authDomain: 'crudfluets.firebaseapp.com',
    storageBucket: 'crudfluets.appspot.com',
    measurementId: 'G-4GD4W1Y4L1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwZPedRwLMzIeVZI8-vTGjsrqKvc38F3A',
    appId: '1:182489347069:android:93abb50d2239014ff79f94',
    messagingSenderId: '182489347069',
    projectId: 'crudfluets',
    storageBucket: 'crudfluets.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEpjg5ATeSqcIcZ2ZU8PCrSf0WsSgOEYo',
    appId: '1:182489347069:ios:b3b60f26f50f16d8f79f94',
    messagingSenderId: '182489347069',
    projectId: 'crudfluets',
    storageBucket: 'crudfluets.appspot.com',
    iosClientId: '182489347069-nna136hlglrs6pmdqfvstrn94dqtcodf.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEpjg5ATeSqcIcZ2ZU8PCrSf0WsSgOEYo',
    appId: '1:182489347069:ios:b3b60f26f50f16d8f79f94',
    messagingSenderId: '182489347069',
    projectId: 'crudfluets',
    storageBucket: 'crudfluets.appspot.com',
    iosClientId: '182489347069-nna136hlglrs6pmdqfvstrn94dqtcodf.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );
}
